### PR TITLE
Make html embedded GSA requests possible

### PR DESCRIPTION
**Pull request by Marthyn**
I've made it possible to do embedded html requests, so there's no XML to be parsed, just raw HTML. 

It's quite crude at the moment, could be made a little prettier. Let me know if you're interested in this functionality. Then i might make a seperate embedded_search method in the facade, so we can do without the if statements. Otherwise we'll keep using it as a fork.

### CODE REVIEW

**Comment by daniel-jerome-long** [comment]
looks good, thx Marthyn :+1:

**Comment by daniel-jerome-long** [comment]
@Marthyn go ahead and describe the embedded html feature in the [README.md](https://github.com/1000Bulbs/gsa/blob/master/README.md) if you get a chance and/or add anything else.

**Comment by Marthyn** [comment]
Yeah I will,
Are you gonna bump the version or shall I do that too?
Sent from my iPhone




On Thu, Jul 9, 2015 at 8:39 AM -0700, "Daniel Long" <notifications@github.com> wrote:
@Marthyn go ahead and describe the embedded html feature in the [README.md](https://github.com/1000Bulbs/gsa/blob/master/README.md) if you get a chance and/or add anything else.

---

**Comment by daniel-jerome-long** [comment]
It’s been bumped.

https://rubygems.org/gems/gsa/versions/0.11.5

Thanks again — feel free to suggest additional improvements.

On Jul 9, 2015, at 10:42 AM, Marthyn Olthof <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah I will,
Are you gonna bump the version or shall I do that too?
Sent from my iPhone




On Thu, Jul 9, 2015 at 8:39 AM -0700, "Daniel Long" <notifications@github.com<mailto:notifications@github.com>> wrote:
@Marthyn go ahead and describe the embedded html feature in the [README.md](https://github.com/1000Bulbs/gsa/blob/master/README.md) if you get a chance and/or add anything else.

---

**Comment by Marthyn** [comment]
Perfect

Sent from my iPhone




On Thu, Jul 9, 2015 at 8:44 AM -0700, "Daniel Long" <notifications@github.com> wrote:
It’s been bumped.

https://rubygems.org/gems/gsa/versions/0.11.5

Thanks again — feel free to suggest additional improvements.

On Jul 9, 2015, at 10:42 AM, Marthyn Olthof <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah I will,
Are you gonna bump the version or shall I do that too?
Sent from my iPhone




On Thu, Jul 9, 2015 at 8:39 AM -0700, "Daniel Long" <notifications@github.com<mailto:notifications@github.com>> wrote:
@Marthyn go ahead and describe the embedded html feature in the [README.md](https://github.com/1000Bulbs/gsa/blob/master/README.md) if you get a chance and/or add anything else.

---
Reply to this email directly or view it on GitHub:
https://github.com/1000Bulbs/gsa/pull/3#issuecomment-120037910

—
Reply to this email directly or view it on GitHub<https://github.com/1000Bulbs/gsa/pull/3#issuecomment-120040663>.



---

**Pull request merged**
